// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/banks": {
            "get": {
                "description": "Returns available banks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "List banks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_modules_banks_catalog_transport_http.BankResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_catalog_transport_http.BankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/beeline/sims": {
            "get": {
                "description": "Returns all registered Beeline SIM cards.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline sims"
                ],
                "summary": "List Beeline SIMs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.SimResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers a Beeline SIM by 10-digit phone number without +7.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline sims"
                ],
                "summary": "Create Beeline SIM",
                "parameters": [
                    {
                        "description": "SIM payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.CreateSimRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.SimResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/beeline/sims/{number}": {
            "get": {
                "description": "Returns a Beeline SIM by phone number.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline sims"
                ],
                "summary": "Get Beeline SIM",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.SimResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Beeline SIM and its payment history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline sims"
                ],
                "summary": "Delete Beeline SIM",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/beeline/sims/{number}/config": {
            "get": {
                "description": "Returns config with effective balance after payment history for the SIM.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline config"
                ],
                "summary": "Get Beeline SIM config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.ConfigResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/beeline/sims/{number}/config/balance": {
            "patch": {
                "description": "Updates initial balance for the SIM. Effective balance subtracts payment totals from history.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline config"
                ],
                "summary": "Update Beeline SIM base balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Balance update payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.UpdateBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/beeline/sims/{number}/payments": {
            "get": {
                "description": "Returns payment history for the SIM.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline payments"
                ],
                "summary": "List Beeline SIM payments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.PaymentResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a manual payment for the SIM. Use direction=outgoing for mobile commerce charge (requires receiverCard, min 924 RUB, 6.5%% commission). Use direction=incoming for balance refill (no card, no commission).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline payments"
                ],
                "summary": "Create Beeline SIM payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payment payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/beeline/sims/{number}/payments/{id}": {
            "get": {
                "description": "Returns a single payment by id for the SIM.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline payments"
                ],
                "summary": "Get Beeline SIM payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.PaymentResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a payment from the SIM history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline payments"
                ],
                "summary": "Delete Beeline SIM payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates a payment for the SIM. Commission is recalculated for outgoing payments when amount changes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "beeline payments"
                ],
                "summary": "Update Beeline SIM payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "10-digit phone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payment update payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.UpdatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_beeline_transport_http.BeelineErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config": {
            "get": {
                "description": "Returns Rocketbank config.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank config"
                ],
                "summary": "Get Rocketbank config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.ConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/balance": {
            "patch": {
                "description": "Updates only Rocketbank balance. Full config updates are not allowed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank config"
                ],
                "summary": "Update Rocketbank balance",
                "parameters": [
                    {
                        "description": "Balance update payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.UpdateBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/client-info": {
            "patch": {
                "description": "Updates only Rocketbank client info. Full config updates are not allowed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank client info"
                ],
                "summary": "Update Rocketbank client info",
                "parameters": [
                    {
                        "description": "Client info update payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.UpdateClientInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history": {
            "get": {
                "description": "Returns Rocketbank configured history items.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank history"
                ],
                "summary": "List Rocketbank history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes all configured Rocketbank history items.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank history"
                ],
                "summary": "Clear Rocketbank history",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/card-transfer": {
            "post": {
                "description": "Creates a Rocketbank card transfer history item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank card transfer"
                ],
                "summary": "Create Rocketbank card transfer history item",
                "parameters": [
                    {
                        "description": "Card transfer payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.CardTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/cash-transfer": {
            "post": {
                "description": "Creates a Rocketbank cash transfer history item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank cash transfer"
                ],
                "summary": "Create Rocketbank cash transfer history item",
                "parameters": [
                    {
                        "description": "Cash transfer payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.CashTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/items/{id}": {
            "get": {
                "description": "Returns Rocketbank configured history item by transaction id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank history"
                ],
                "summary": "Get Rocketbank history item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "History transaction id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes Rocketbank configured history item by transaction id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank history"
                ],
                "summary": "Delete Rocketbank history item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "History transaction id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/items/{id}/card-transfer": {
            "patch": {
                "description": "Updates a Rocketbank card transfer history item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank card transfer"
                ],
                "summary": "Update Rocketbank card transfer history item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "History transaction id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Card transfer patch payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.UpdateCardTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/items/{id}/cash-transfer": {
            "patch": {
                "description": "Updates a Rocketbank cash transfer history item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank cash transfer"
                ],
                "summary": "Update Rocketbank cash transfer history item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "History transaction id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cash transfer patch payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.UpdateCashTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/items/{id}/sbp-transfer": {
            "patch": {
                "description": "Updates a Rocketbank SBP transfer history item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank sbp transfer"
                ],
                "summary": "Update Rocketbank SBP transfer history item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "History transaction id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SBP transfer patch payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.UpdateSBPTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/banks/rocketbank/config/history/sbp-transfer": {
            "post": {
                "description": "Creates a Rocketbank SBP transfer history item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rocketbank sbp transfer"
                ],
                "summary": "Create Rocketbank SBP transfer history item",
                "parameters": [
                    {
                        "description": "SBP transfer payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.SBPTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse"
                        }
                    }
                }
            }
        },
        "/sms-agent/v1/messages": {
            "get": {
                "security": [
                    {
                        "SMSAgentKey": []
                    }
                ],
                "description": "Returns queued SMS messages for the Android agent to deliver locally via Shizuku.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sms agent"
                ],
                "summary": "Poll pending SMS for mobile agent",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max messages",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_modules_smsagent_transport_http.MessageResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AgentErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AgentErrorResponse"
                        }
                    }
                }
            }
        },
        "/sms-agent/v1/messages/{id}/ack": {
            "post": {
                "security": [
                    {
                        "SMSAgentKey": []
                    }
                ],
                "description": "Marks a queued SMS as delivered or failed after the agent attempts local injection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sms agent"
                ],
                "summary": "Acknowledge SMS delivery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Delivery result",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AckMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AgentErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AgentErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AgentErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_smsagent_transport_http.AgentErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.AccessErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "http.AccessResponse": {
            "type": "object",
            "properties": {
                "bankCode": {
                    "type": "string"
                },
                "bankId": {
                    "type": "integer"
                },
                "bankName": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "grantReason": {
                    "type": "string"
                },
                "grantedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "revokeReason": {
                    "type": "string"
                },
                "revokedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "http.AuthErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "http.AuthResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/http.AuthUserResponse"
                }
            }
        },
        "http.AuthUserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.CreateUserRequest": {
            "type": "object",
            "required": [
                "login",
                "role"
            ],
            "properties": {
                "isActive": {
                    "type": "boolean"
                },
                "login": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "http.GrantAccessRequest": {
            "type": "object",
            "required": [
                "bankId",
                "expiresAt",
                "grantReason",
                "userId"
            ],
            "properties": {
                "bankId": {
                    "type": "integer"
                },
                "expiresAt": {
                    "type": "string"
                },
                "grantReason": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "http.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "http.LogoutRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "http.RefreshRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "http.RevokeAccessRequest": {
            "type": "object",
            "required": [
                "bankId",
                "revokeReason",
                "userId"
            ],
            "properties": {
                "bankId": {
                    "type": "integer"
                },
                "revokeReason": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "http.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "isActive": {
                    "type": "boolean"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "http.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.BeelineErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.ConfigResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "baseBalance": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "paymentsTotal": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.CreatePaymentRequest": {
            "type": "object",
            "required": [
                "amount",
                "paidAt"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 13000
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "outgoing",
                        "incoming"
                    ],
                    "example": "outgoing"
                },
                "paidAt": {
                    "type": "string",
                    "example": "2026-05-23T12:07:47+03:00"
                },
                "receiverCard": {
                    "type": "string",
                    "example": "220094**0028"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.CreateSimRequest": {
            "type": "object",
            "required": [
                "number"
            ],
            "properties": {
                "number": {
                    "type": "string",
                    "example": "9680659702"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.PaymentResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "commission": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "paidAt": {
                    "type": "string"
                },
                "receiverCard": {
                    "type": "string"
                },
                "simNumber": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.SimResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.UpdateBalanceRequest": {
            "type": "object",
            "required": [
                "balance"
            ],
            "properties": {
                "balance": {
                    "type": "number",
                    "example": 50000
                }
            }
        },
        "internal_modules_banks_beeline_transport_http.UpdatePaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 13000
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "outgoing",
                        "incoming"
                    ],
                    "example": "outgoing"
                },
                "paidAt": {
                    "type": "string",
                    "example": "2026-05-23T12:07:47+03:00"
                },
                "receiverCard": {
                    "type": "string",
                    "example": "220094**0028"
                }
            }
        },
        "internal_modules_banks_catalog_transport_http.BankErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_catalog_transport_http.BankResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.CardTransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "balanceBefore",
                "bankId",
                "direction",
                "recipientCardNumber",
                "time"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "balanceBefore": {
                    "type": "number",
                    "example": 22096.74
                },
                "bankId": {
                    "type": "string",
                    "example": "tbank"
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "OUTGOING",
                        "INCOMING"
                    ],
                    "example": "OUTGOING"
                },
                "recipientCardNumber": {
                    "type": "string",
                    "example": "1234 5678 9100 0000"
                },
                "time": {
                    "type": "string",
                    "example": "2026-05-16T22:14:12+0700"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.CashTransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "balanceBefore",
                "direction",
                "time"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 8000
                },
                "balanceBefore": {
                    "type": "number",
                    "example": 22096.74
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "OUTGOING",
                        "INCOMING"
                    ],
                    "example": "OUTGOING"
                },
                "time": {
                    "type": "string",
                    "example": "2026-05-02T11:08:52+0700"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.ClientInfoResponse": {
            "type": "object",
            "properties": {
                "cardNumber": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.ConfigResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "clientInfo": {
                    "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.ClientInfoResponse"
                },
                "createdAt": {
                    "type": "string"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_banks_rocketbank_transport_http.HistoryResponse"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.HistoryResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "balanceBefore": {
                    "type": "number"
                },
                "bankId": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "operationFirstName": {
                    "type": "string"
                },
                "operationLastName": {
                    "type": "string"
                },
                "operationMiddleName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "recipientCardNumber": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.RocketbankErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.SBPTransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "balanceBefore",
                "bankId",
                "direction",
                "operationFirstName",
                "operationLastName",
                "operationMiddleName",
                "time"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 50
                },
                "balanceBefore": {
                    "type": "number",
                    "example": 190
                },
                "bankId": {
                    "type": "string",
                    "example": "tbank"
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "OUTGOING",
                        "INCOMING"
                    ],
                    "example": "OUTGOING"
                },
                "operationFirstName": {
                    "type": "string",
                    "example": "Азат"
                },
                "operationLastName": {
                    "type": "string",
                    "example": "Гайнутдинов"
                },
                "operationMiddleName": {
                    "type": "string",
                    "example": "Аликович"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+79099334005"
                },
                "time": {
                    "type": "string",
                    "example": "2026-05-16T22:14:12+0700"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.UpdateBalanceRequest": {
            "type": "object",
            "required": [
                "balance"
            ],
            "properties": {
                "balance": {
                    "type": "number",
                    "example": 99999
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.UpdateCardTransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "balanceBefore": {
                    "type": "number",
                    "example": 22096.74
                },
                "bankId": {
                    "type": "string",
                    "example": "tbank"
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "OUTGOING",
                        "INCOMING"
                    ],
                    "example": "OUTGOING"
                },
                "recipientCardNumber": {
                    "type": "string",
                    "example": "1234 5678 9100 0000"
                },
                "time": {
                    "type": "string",
                    "example": "2026-05-16T22:14:12+0700"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.UpdateCashTransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 8000
                },
                "balanceBefore": {
                    "type": "number",
                    "example": 22096.74
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "OUTGOING",
                        "INCOMING"
                    ],
                    "example": "OUTGOING"
                },
                "time": {
                    "type": "string",
                    "example": "2026-05-02T11:08:52+0700"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.UpdateClientInfoRequest": {
            "type": "object",
            "required": [
                "cardNumber",
                "firstName",
                "lastName",
                "middleName",
                "phoneNumber"
            ],
            "properties": {
                "cardNumber": {
                    "type": "string",
                    "example": "40817810000000000000"
                },
                "firstName": {
                    "type": "string",
                    "example": "Иван"
                },
                "lastName": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middleName": {
                    "type": "string",
                    "example": "Иванович"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+79001234567"
                }
            }
        },
        "internal_modules_banks_rocketbank_transport_http.UpdateSBPTransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 50
                },
                "balanceBefore": {
                    "type": "number",
                    "example": 190
                },
                "bankId": {
                    "type": "string",
                    "example": "tbank"
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "OUTGOING",
                        "INCOMING"
                    ],
                    "example": "OUTGOING"
                },
                "operationFirstName": {
                    "type": "string",
                    "example": "Азат"
                },
                "operationLastName": {
                    "type": "string",
                    "example": "Гайнутдинов"
                },
                "operationMiddleName": {
                    "type": "string",
                    "example": "Аликович"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+79099334005"
                },
                "time": {
                    "type": "string",
                    "example": "2026-05-16T22:14:12+0700"
                }
            }
        },
        "internal_modules_smsagent_transport_http.AckMessageRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "deviceId": {
                    "type": "string",
                    "example": "abc123"
                },
                "errorMessage": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "delivered"
                }
            }
        },
        "internal_modules_smsagent_transport_http.AgentErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_modules_smsagent_transport_http.MessageResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bank": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rebellion Banking APII",
	Description:      "API documentation for .",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
